
            <p><strong><span style="color: #000000; font-size: medium;"><span style="color: #333333;">Stay connected with us</span>!<br /></span></strong></p>
            <p><span style="font-size: small;">Join us on social profiles to not <br />miss exclusive offers and deals!</span></p>
            <p><span style="font-size: small;">&nbsp;<a href="http://www.facebook.com"><img src="{{media url="wysiwyg/popup/facebook2.png"}}" alt="" width="48" height="48" /></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.twitter.com"><img src="{{media url="wysiwyg/popup/twitter2.png"}}" alt="" width="48" height="48" /></a>&nbsp; &nbsp;&nbsp;&nbsp; <a href="http://plus.google.com/&lrm;"><img src="{{media url="wysiwyg/popup/gplus2.png"}}" alt="" width="48" height="48" /></a><br /><span style="font-size: small;">Facebook&nbsp;&nbsp; &nbsp;&nbsp; Twitter</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Gplus<br /><br /></span></p>


