
            <p><strong><span style="color: #000000; font-size: medium;"><span style="color: #333333;">Stay connected with us</span>!<br /></span></strong></p>
            <p><span style="font-size: small;">Join us on social profiles to not <br />miss exclusive offers and deals!</span></p>
            <table style="width: 100%;margin-top:20px" border="0">
                <tbody>
                <tr>
                    <td style="padding: 0 20px 0 0;">
                        <a href="http://www.facebook.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-fb.png')?>" alt="" width="48" height="48" /></a>
                    </td>
                    <td style="padding: 0 20px;">
                        <a href="http://www.twitter.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-twitter.png')?>" alt="" width="48" height="48" /></a>
                    </td>
                    <td style="padding: 0 20px;">
                        <a href="http://www.facebook.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-gplus.png')?>" alt="" width="48" height="48" /></a>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 0 20px 0 0;">
                        <span style="font-size: small;">Facebook</span>
                    </td>
                    <td style="padding: 0 20px;">
                        <span style="font-size: small;">Twitter</span>
                    </td>
                    <td style="padding: 0 20px;">
                        <span style="font-size: small;">Gplus</span>
                    </td>
                </tr>
                </tbody>
            </table>