

<div id="sc-popup07" class="modal fade sc-popup07" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <a class="dialogClose style1 overlay2" data-dismiss="modal" data-target="#sc-popup07"></a>
            <table style="background-color: #26292a; width: 770px; height: 54px;" border="0">
                <tbody>
                <tr>
                    <td>
                        <p style="line-height: 34px;"><span style="font-size: x-large;"><strong><span style="color: #ffffff;">&nbsp; Promo title goes here Lorem ipsum dolor!</span></strong></span></p>
                    </td>
                    <td style="width: 160px;">
                        <p><a href="#"  class="popupButton size3">Click here >></a></p>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>