<div class="sc-popup7">
<table style="background-color: #26292a; width:100%; height: 54px;" border="0">
    <tbody>
    <tr>
        <td>
            <p style="line-height: 34px;"><span style="font-size: x-large;"><strong><span style="color: #ffffff;">SPECIAL DEAL: X% OFF Y PRODUCT </span></strong></span></p>
        </td>
        <td style="width: 160px;">
            <p><a href="#"  class="popupButton size3">Grab it now >></a></p>
        </td>
    </tr>
    </tbody>
</table>
</div>