<div class="modal-header">
    <h4 class="modal-title">Modal title</h4>
</div>
<div class="modal-body">
    <p>One fine body…</p>
</div>
<div class="modal-footer" style="
    padding-right: 0;
">
    <button class="btn btn-default" type="button" data-dismiss="modal" style="
    background: #000;
    border: 0 none;
    padding: 5px 20px;
">Close
    </button>
    <button class="btn btn-primary" type="button" style="
    background: green;
    color: #fff;
    border: 0 none;
    padding: 5px 20px;
    margin-right: 0;
">Save changes
    </button>
</div>


