<div class="sc-popup13">
    <p style="font-size:20px;color:#333;text-transform: uppercase">Register to get <strong style="color:red">$5</strong>.</p>
    <div style="padding:0 20px"><?php echo $this->getLayout()->createBlock('customer/form_register')->setTemplate('campaign/popup/form/register-type1.phtml')->toHtml(); ?></div>
</div>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j('#sc-login').hide();
    $j('.campaign-login').click(function(){
        $j('#sc-register-form').hide();
        $j('#sc-login').show();

    });
    $j('.campaign-register').click(function(){
        $j('#sc-login').hide();
        $j('#sc-register-form').show();

    });

</script>