<div class="sc-popup14">
    <div style="padding:0 20px"><?php echo $this->getLayout()->createBlock('core/template')->setArea('frontend')->setTemplate('campaign/popup/form/register-type2.phtml')->toHtml(); ?></div>
</div>
<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j('.sc-login').hide();
    $j('.campaign-login').click(function(){
        $j('.form-register-campaign').hide();
        $j('.sc-login').show();

    });
    $j('.campaign-register').click(function(){
        $j('.sc-login').hide();
        $j('.form-register-campaign').show();

    });

</script>