<div class="row"><div class="wrap-static-popup">
        <div class="image-left col-md-5 col-sm-5"><img src="{{skin url='images/campaign/img-left.png'}}" alt="Summer holiday" width="100%" height="100%" /></div>
        <div class="col-md-7 col-sm-7">
            <div class="title">
                <h4>SimiCart &amp; Magento co-host</h4>
                <span class="line">&nbsp;</span></div>
            <div class="title-small">
                <h3>FREE training Webinar</h3>
                <span class="clock">{{block type="campaign/countdown" locate="popup"}}</span></div>
            <div class="description">
                <h5>How to build mobile apps for Magento sites</h5>
                <ul>
                    <li>Learn to build your Magento mobile apps. Without coding</li>
                    <li>Directly discuss with our experts in real-time Q&amp;A session</li>
                </ul>
            </div>
            <div class="actions">
                <div class="button button1"><a rel="nofollow" target="_blank" {{block type="campaign/popup" template="campaign/gapopup/ga_button_static.phtml"}}><span>Gimme more info</span></a></div>
                <div class="button button2"><a data-dismiss="modal"><span>I'm not interested</span></a></div>
            </div>
        </div>
    </div>
</div>