<div class="content step2">
    <div class="popup-treat-game">
        <h2>To check &amp; use points, please enter email used for purchasing:</h2>
        <form id="halloween-email" class="form-inline" action="" method="">
            <div class="form-group"><input class="form-control required-entry validate-email" type="text" name="email" /> <button class="btn btn-submit">Ok, let's check my result</button><p class="error-message">:(</p></div>
        </form></div>
</div>