<div id="close-popup" class="close-popup" data-dismiss="modal">
    <img src="{{skin url='images/campaign/christmas/close.png'}}"/>
</div>
<div class="content step1">
    <div class="christmas">
        <div class="title"><span class="text-title">&nbsp;</span></div>
        <div class="text-content">
            <h2>Select your favourite <span style="font-weight: bold;">Christmas stocking</span> to receive reward points as Xmas gift
            </h2>
            <h2>(Up to <span style="color: #940f13;font-weight: bold;"><span style="font-size:24px">$30</span>-valued points</span> for discount in next purchase)</h2>
        </div>
        <div class="game-shoes">
            <div class="rope"><span class="the-rope"></span></div>
            <ul>
                <li class="shoe-1 charactor ctrl-char-1">
                    <span class="t1">&nbsp;</span>
                    <span class="t2">&nbsp;</span>
                </li>
                <li class="shoe-2 charactor ctrl-char-2">
                    <span class="t1">&nbsp;</span>
                    <span class="t2">&nbsp;</span>
                </li>
                <li class="shoe-3 charactor ctrl-char-3">
                    <span class="t1">&nbsp;</span>
                    <span class="t2">&nbsp;</span>
                </li>
                <li class="shoe-4 charactor ctrl-char-4">
                    <span class="t1">&nbsp;</span>
                    <span class="t2">&nbsp;</span>
                </li>
                <li class="shoe-5 charactor ctrl-char-5 last">
                    <span class="t1">&nbsp;</span>
                    <span class="t2">&nbsp;</span>
                </li>
            </ul>
        </div>
    </div>
</div>