<!--campaign/header_text.phtml-->
<?php
 $headertext = $this->getHtml();
if(count($headertext) > 0): ?>
    <div id="header-campaign-slide" class="owl-carousel">
        <?php foreach($headertext as $header):?>
         <div class="header-item">
              <?php echo $header; ?>
         </div>
         <?php endforeach; ?>
    </div>
<?php endif;?>

<script>
    var $j = jQuery.noConflict();
    $j(document).ready(function() {
        $j("#header-campaign-slide").owlCarousel({
            navigation : true, // Show next and prev buttons
            slideSpeed : 500,
            paginationSpeed : 500,
            singleItem:true,
            autoPlay: true
        });
    });
</script>