<?php
$canAddJquery = true;
$canAddOwl = true;
$existBootstrap = false;
$existJQCookie = false;
if($head = $this->getLayout()->getBlock('head')) {
    foreach ($head->getData('items') as $js => $item) {
        if (strpos($js, 'jquery') != false) {
            $canAddJquery = false;
        }
        if (preg_match('#.*owl\.carousel.*\.js$#', $js)) {
            $canAddOwl = false;
        }
        if (preg_match('#.*bootstrap.*\.js$#', $js)) {
            $existBootstrap = true;
        }
        if (preg_match('#.*jquery\.cookie.*\.js$#', $js)) {
            $existJQCookie = true;
        }
    }
}

?>
<!--Start Magestore Supercampaign js-->
    <?php if($canAddJquery): ?>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magestore/campaign/jquery-1.10.1.min.js'); ?>"></script>
    <?php endif; ?>
    <?php if(!$existBootstrap): ?>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magestore/campaign/bootstrap.min.js'); ?>"></script>
    <?php endif; ?>
    <?php if($canAddOwl): ?>
        <!--<script type="text/javascript" src="<?php /*echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); */?>magestore/campaign/owl.carousel.min.js"></script>-->
    <?php endif; ?>

    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magestore/campaign/general.js'); ?>"></script>

<!--End Magestore Supercampaign js-->
