<!--campaign/smmodal.phtml-->

<?php $popups = $this->getAllPopupAvailable(); ?>

<?php foreach ($popups as $key => $popup): ?>

    <?php
    //Zend_debug::dump($popup->getData());
    $segmentpopup = Mage::helper('campaign')->checkSegmentpopup();
    $cookiepopup = Mage::helper('campaign')->checkCookiepopup();
    $stylepopup = Mage::helper('campaign')->checkStylepopup();
    ?>
        <div id="sc-popup<?php echo $popup->getData('popup_id') ?>"
             class="modal fade sc-popup<?php echo $popup->getData('template_code') ?>" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <a class="dialogClose style1 overlay2" data-dismiss="modal"
                       data-target=".sc-popup<?php echo $popup->getData('template_code') ?>"></a>
                    <?php echo $popup->getData('popup_content'); ?>
                </div>
            </div>
        </div>
<?php endforeach; ?>

<script type="text/javascript">
    var dataPopup = [
    <?php $count = 0; $total = count($popups) ?>
    <?php foreach ($popups as $key => $popup): ?>
        <?php echo json_encode($popup->getData()) ?>
        <?php if($count < $total-1) echo ', ' ?>
        <?php $count++; ?>
    <?php endforeach; ?>
    ];

    var Popups = [];
    for(var id = 0; id<dataPopup.length; id++){
        var Popup = new Scpopup();
        Popup.idPopup =  dataPopup[id].popup_id;
        Popup.templateCode = dataPopup[id].template_code;
        Popup.effect = dataPopup[id].appear_effect;
        Popup.borderSize = dataPopup[id].border_size;
        Popup.borderColor = dataPopup[id].border_color;
        Popup.paddingSize = dataPopup[id].padding;
        Popup.width = dataPopup[id].width;
        Popup.bgColor = dataPopup[id].popup_background;
        Popup.overlayColor = dataPopup[id].overlay_color;
        Popup.closeStyle = dataPopup[id].close_style;
        Popup.cornerRadius = dataPopup[id].corner_style;
        Popup.horizontalPosition = dataPopup[id].horizontal_position;
        Popup.verticalPosition = dataPopup[id].vertical_position;
        Popup.horizontalPx = dataPopup[id].horizontal_px;
        Popup.verticalPx = dataPopup[id].vertical_px;
        Popup.secondDelay = dataPopup[id].seconds_delay;
        Popup.showWhen = dataPopup[id].show_when;
        Popup.status = dataPopup[id].status;

        Popups[id] = Popup;
        $j(window).bind("load", function () {
            Popups[1].addCssToHead('http://localhost.com/campaign/skin/frontend/rwd/default/');
            Popups[1].showPopup();
            Popups[1].runEffect();
        });
    }

</script>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    $j('#myModal').modal('show');
</script>