<div id="sc-popup05" class="modal fade sc-popup05" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <a class="dialogClose style1 overlay2" data-dismiss="modal" data-target="#sc-popup05"></a>
            <h2 style="text-align: center;"><span style="font-size: x-large;"><strong><span style="color: #f5f5fe; text-shadow: 1px 1px #000;">Subscribe to our newsletter</span></strong></span></h2>
            <p style="text-align: center;"><span style="color: #f5f5f5;">Enter your email address to hear about exclusive savings and news!</span></p>
            <p style="text-align: center;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('campaign/popup/form/subscribe-type5.phtml')->toHtml(); ?></p>
            <p style="text-align: center;"><span style="font-size: x-small; color: #f5f5f5;">*We will never share your information</span></p>
        </div>
    </div>
</div>
