<h3 style="font-size:24px;color:#333;text-align:center;font-weight:600">KEEP IN TOUCH WITH US</h3>
<p style="font-size:12px;color:#333;text-align:center">This is a custom block and you can add any content easy from admin panel. Also from admin panel you can set background color/image and adjust the width of this popup</p>
<p style="font-size:18px;text-align:center">Be the first to receive our exclusive offers</p>
<div style="text-align: left;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type4.phtml')->toHtml(); ?></div>
<h3 style="font-size:24px;color:#333;text-align:center">More ways to stay connected:</h3>
<table style="width: 100%;margin-top:20px" border="0">
    <tbody>
    <tr>
        <td style="padding: 0 20px 0 0;">
            <a href="http://www.facebook.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-fb.png')?>" alt="" width="48" height="48" /></a>
        </td>
        <td style="padding: 0 20px;">
            <a href="http://www.twitter.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-twitter.png')?>" alt="" width="48" height="48" /></a>
        </td>
        <td style="padding: 0 20px;">
            <a href="http://www.facebook.com"><img src="<?php echo $this->getSkinUrl('images/campaign/popup/icon-gplus.png')?>" alt="" width="48" height="48" /></a>
        </td>
    </tr>
    </tbody>
</table>