
            <table
                style="vertical-align: top;border-collapse: separate;border-spacing: 25px;background-size: contain; background-image:url(http://localhost.com/campaign/skin/frontend/base/default/images/campaign/image1.jpg); width: 100%;"
                border="0">
                <tbody>
                <tr>
                    <td style="background-color: rgba(255, 255, 255, 0.85); padding: 20px 10px;">
                        <p style="text-align: center; font-size: 20px; margin: 0;"><span
                                style="border-bottom: 1px solid silver; padding-bottom: 10px;">Enter your e-mail to get</span>
                        </p>
                        <p class="fontBig"
                           style="text-shadow: -1px 0px black, 0px 1px black, 1px 0px black, 0px -1px black; font-weight: bold; font-size: 70px; color: #ffffff; text-align: center; margin-bottom: 20px;">
                            -50% OFF</p>
                        <div style="text-align: center;"> <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe.phtml')->toHtml(); ?></div>
                        <div style="text-align: center;">
                            <p style="font-size: 15px; margin-top: 20px;">Hurry up, the offer will expire in the
                                next</p>

                            <div style="text-align: center;">&nbsp;</div>
                            <div style="text-align: center;">&nbsp;</div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
