            <div class="sc-popup15">
                <table style="background-image: url(<?php echo Mage::getDesign()->setArea('frontend')->getSkinUrl('images/campaign/popup/image-2-new.png') ?>); background-position: right; background-size:auto 100%; background-repeat: no-repeat; width: 100%;" border="0">
                    <tbody>
                    <tr>
                        <td style="padding: 30px;">
                            <p class="fontBig" style="text-align: left; font-size: 26px; font-style: italic; margin: 0;">Wanna know</p>
                            <p class="fontBig" style="text-align: left; font-size: 70px; line-height: 1; margin: 0;">SPECIAL</p>
                            <p class="fontBig" style="text-align: left; font-size: 70px; line-height: 1; font-weight: bold; margin: 0; color: #ff1176;">DISCOUNTS?</p>
                            <p class="popupSmall" style="text-align: left; font-size: 24px; line-height: 1; margin: 20px 0; font-style: italic;">Enter your email & get all <br />exclusive savings & news right into your inbox!</p>
                            <div style="text-align: left;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type2.phtml')->toHtml(); ?></div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>

