<div class="sc-popup20">
            <h1 style="text-align: center;"><span style="color: #000000;"><strong><span style="font-size: 25px;">Free Hacks & Tips<br /></span></strong></span></h1>
            <p style="text-align: center;">Enter your information below to receive our weekly newsletter</p>
            <p style="text-align: left;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type20.phtml')->toHtml(); ?></p>
            <p style="text-align: left;"><span style="font-size: x-small; color:#DDDDDD;">*We will never share your information</span></p>
</div>