
<div id="sc-popup04" class="modal fade sc-popup04" role="dialog">

    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <a class="dialogClose style1 overlay2" data-dismiss="modal" data-target="#sc-popup04"></a>
            <h1 style="text-align: left;"><span style="color: #ffffff;"><strong><span style="font-size: x-large; text-shadow: 1px 1px #000;">Hear about exclusive savings!<br /></span></strong></span></h1>
            <p style="text-align: left;">Enter your email address to hear about exclusive savings and news!</p>
            <p style="text-align: left;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('campaign/popup/form/subscribe-type4.phtml')->toHtml(); ?></p>
            <p style="text-align: left;"><span style="font-size: x-small;">*We will never share your information</span></p>
        </div>
    </div>
</div>
