<div class="sc-popup10">
    <h1 style="background-color: #4c4b4b; color: white; line-height: 42px;"><span style="color: #ffffff; font-size: 30px;padding: 0 20px">10% OFF. Join discount club!<br /></span></h1>
    <div style="font-size: 12px;padding: 0 20px 20px">Join our discount club and get <strong>10% OFF</strong> now. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo, nisi mollis mattis laoreet</div>
    <div style="padding:0 20px"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type4.phtml')->toHtml(); ?></div>
    <div style="padding:0 20px 20px"><span style="font-size: x-small;">*We will never share your information</span></div>
</div>