            <table style="height: 376px; width: 100%; background-color: #eaeaea;" border="0">
                <tbody>
                <tr>
                    <td style="width: 250px; text-align: center; padding: 15px;">
                        <p style="font-size: 40px;"><span style="border-bottom: 1px solid black; padding-bottom: 20px;">BIG CHANGE</span></p>
                        <p style="line-height: 1; font-size: 17px; margin: 35px 0 20px;">Backing big ideas to catalyse <span style="font-weight: bold;">change</span>change for young people in <span style="font-weight: bold;">the UK</span>.</p>
                        <p style="clear: both; margin: 0 auto;"><strong><span style="color: #9e6dc6;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('campaign/popup/form/subscribe-type3.phtml')->toHtml(); ?></span></strong></p>
                        <p class="dialogCloseCustom" data-dismiss="modal" data-target="#sc-popup03" style="text-decoration: underline; font-size: 17px; margin-top: 12px;">No thanks</p>
                    </td>
                    <td class="imageField" style="width: 304px;"><img src="<?php echo $this->getSkinUrl('images/campaign/image-3.jpg')?>" alt="" width="100%" height="376" /></td>
                </tr>
                </tbody>
            </table>
