<div class="sc-popup15">
    <table
        style="vertical-align: top; background-image:url(<?php echo Mage::getDesign()->setArea('frontend')->getSkinUrl('images/campaign/bg-popup21.png')?>); width: 100%; background-repeat: round;"
        border="0">
        <tbody>
        <tr>
            <td style="width: 300px;">

            </td>

            <td style="padding: 20px 10px;">
                <p style="text-align: left; font-size: 13px; margin: 0; line-height: 25px; margin-bottom: 10px;"><span>Up to</span></p>
                <p style="text-align: left; font-size: 60px; margin: 0; line-height: 35px;"><span>30% OFF</span></p>

                <p style="text-align: left; font-size: 13px; margin: 0; line-height: 25px; margin: 15px 0px 15px 0px;"><span>Original Price on Select items</span></p>
                <div style="text-align: center;">

                    <div style="text-align: center; width: 200px; height: 55px; background: #000000; margin-bottom: 70px;"><a href="#" target="_blank" style="text-decoration: none; line-height: 50px; color:#FFFFFF;">VIEW ALL</a></div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>