<div class="sc-popup16">
<table style="min-height: 376px; width: 100%;" border="0">
                <tbody>
                <tr>
                    <td class="imageField" style="width: 250px;"><img src="<?php echo Mage::getDesign()->setArea('frontend')->getSkinUrl('images/campaign/image-16.png')?>" alt="" width="100%" height="376" /></td>
                    <td style="width: 300px; text-align: center; padding: 15px;">
                        <p style="font-size: 35px; line-height: 100px;"><span style="margin-bottom: 40px;">GET IN THE KNOW</span></p>
                        <p style="font-size: 15px;"><span style="margin-bottom: 30px; text-align: center;">Be the first to hear about exclusive offers, new arrivals, and move</span></p>
                        <p style="clear: both; margin: 0 auto;"><strong><span style="color: #9e6dc6;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type16.phtml')->toHtml(); ?></span></strong></p>
                    </td>
                </tr>
                </tbody>
            </table>
</div>