<div class="sc-popup17">
<table style="min-height: 376px; width: 100%;" border="0">
                <tbody>
                <tr>
                    <td style="width: 250px; text-align: left; padding: 15px;">
                        <p style="font-size: 40px;"><span style="padding-bottom: 10px; color: #363636;">NEW COLLECTION</span></p>
                        <p style="line-height: 1; font-size: 17px; margin: 10px 0 65px; color:#acacac;">sport clothing & accessories</p>
                        <p style="clear: both; margin: 0 auto;"><div style="width: 162px; height: 40px; border-radius:3px; padding:0px 15px 15px 15px; text-align: center; background-color:#363636; "><a style="text-decoration: none; line-height: 35px; color: #FFFFEE;" href="#" target="_blank">JOIN ME</a></div></p>
                        <p style="line-height: 1; font-size: 22px; margin: 35px 0 10px; color: #363636;">SPORTCOLLECTION</p>
                        <p style="line-height: 1; font-size: 17px; margin: 5px 0 20px; color: #acacac;">www.example.com</p>
                    </td>
                    <td class="imageField" style="width: 304px;"><img src="<?php echo Mage::getDesign()->setArea('frontend')->getSkinUrl('images/campaign/image-17.png')?>" alt="" width="100%" height="376" /></td>
                </tr>
                </tbody>
            </table>
</div>