<div class="sc-popup6">
            <table style="position:relative;width: 100%; height: 190px;border-spacing: 25px;border-collapse: separate;" border="0" cellspacing="0" cellpadding="10">
                <tbody>
                <tr>
                    <td style="padding-right:195px">
                        <h1><span style="color: #333333;"><strong><span style="font-size: xx-large;">Subscribe to our Discount Club</span></strong></span></h1>
                        <p>Enter your email to get special offers, exclusive discounts & latest news from us.
                            100% Privacy Guarantee!
                        </p>
                        <p>&nbsp;</p>
                    </td>
                    <td>
                        <p><img style="position:absolute;z-index:1;bottom:0;right:0" src="<?php echo Mage::getDesign()->setArea('frontend')->getSkinUrl('images/campaign/popup/img-template06.png')?>" alt="" width="213" height="192" /></p>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="newsletter-form" style="background-color: #03a2b1;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type6.phtml')->toHtml(); ?></div>
</div>