<div class="sc-popup11">
    <h1 style="background-color: #4c4b4b; color: white; line-height: 42px;"><span style="color: #ffffff; font-size: 30px;">10% OFF. Join discount club!<br /></span></h1>
    <p>Join our discount club and get <strong>10% OFF</strong> now. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo, nisi mollis mattis laoreet</p>
    <p>{{widget widget_id="_rer7" type="magebird_popup/list" template="magebird/popup/newsletter/2.phtml" width="100" width_unit="2" button_color="#4c4b4b" button_text_color="#FFFFFF" apply_coupon="1" on_success="1" success_msg="Thank%20you%20for%20your%20subscription!"}}</p>
    <p><span style="font-size: x-small;">*We will never share your information</span></p>
</div>