<div class="sc-popup19">
            <h1 style="text-align: left;"><span style="color: #000000;"><strong><span style="font-size: 25px;">Hear about exclusive savings!<br /></span></strong></span></h1>
            <p style="text-align: left;">Enter your email address to hear about exclusive savings and news!</p>
            <p style="text-align: left;"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setArea('frontend')->setTemplate('campaign/popup/form/subscribe-type19.phtml')->toHtml(); ?></p>
            <p style="text-align: left;"><span style="font-size: x-small; color:#DDDDDD;">*We will never share your information</span></p>
</div>