<div id="close-popup" class="close-popup" data-dismiss="modal">
    <img src="{{skin url='images/campaign/christmas/close.png'}}"/>
</div>
<div class="content step2">
    <div class="christmas">
        <div class="mr-noel"><span>&nbsp;</span></div>
        <div class="form-content">
            <div class="text-content">
                <h2>To check & use points, please enter email used for purchasing:</h2>
            </div>
            <form id="halloween-email" class="form-inline" action="" method="">
                <div class="form-group"><input class="form-control required-entry validate-email" type="text" name="email" /> <button class="btn btn-submit">Yes, view my result</button></div>
                <p class="error-message">:(</p>
            </form>
        </div>
    </div>
</div>
