<div id="close-popup" class="close-popup" data-dismiss="modal">
    <img src="{{skin url='images/campaign/christmas/close.png'}}"/>
</div>
<div class="content step3">
    <div class="christmas">
        <div class="title">
            <span class="text-title3">&nbsp;</span>
        </div>
        <div class="text-content">
            <h2>You received <span class="points-value" style="font-weight: bold;color:#940f13">5 points</span> to get <span class="money-value" style="font-weight: bold;color:#940f13">$5</span> discount in your next order (valid until Dec 31 only)</h2>
            <button id="spend-my-points" class="btn btn-submit" type="button">Use my points now</button>
        </div>
    </div>
    <div class="game-shoes">
        <div class="rope"><span class="the-rope">&nbsp;</span></div>
        <ul>
            <li class="shoe-1 ctrl-c ctrl-char-1">
                <span class="t1">&nbsp;</span>
                <span class="t2">&nbsp;</span>
            </li>
            <li class="shoe-2 ctrl-c ctrl-char-2">
                <span class="t1">&nbsp;</span>
                <span class="t2">&nbsp;</span>
            </li>
            <li class="shoe-3 ctrl-c ctrl-char-3">
                <span class="t1">&nbsp;</span>
                <span class="t2">&nbsp;</span>
            </li>
            <li class="shoe-4 ctrl-c ctrl-char-4">
                <span class="t1">&nbsp;</span>
                <span class="t2">&nbsp;</span>
            </li>
            <li class="shoe-5 ctrl-c ctrl-char-5 last">
                <span class="t1">&nbsp;</span>
                <span class="t2">&nbsp;</span>
            </li>
        </ul>
        <ul class="shoes-points">
            <li class="shoe-1 ctrl-c ctrl-char-1">
                <p class="points-value">10 points</p>
            </li>
            <li class="shoe-2 ctrl-c ctrl-char-2">
                <p class="points-value">10 points</p>
            </li>
            <li class="shoe-3 ctrl-c ctrl-char-3">
                <p class="points-value">10 points</p>
            </li>
            <li class="shoe-4 ctrl-c ctrl-char-4">
                <p class="points-value">10 points</p>
            </li>
            <li class="shoe-5 ctrl-c ctrl-char-5 last">
                <p class="points-value">10 points</p>
            </li>
        </ul>
    </div>
</div>