<div class="content step1">
    <div class="popup-treat-game">
        <div class="game-program"><img src="{{skin url='images/campaign/halloween/treat-game.png'}}" alt="" width="100%" height="100%" /></div>
        <h2>Knock the right door to get "sweet" reward points this Halloween</h2>
        <h2>(Up to <span style="color: #f6a81f;">$30-valued</span> points for discount in next order)</h2>
        <p>Now, click one of the doors to try your luck:</p>
        <div class="treat-game-program">
            <ul>
                <li class="door-1 charactor">&nbsp;</li>
                <li class="door-2 charactor">&nbsp;</li>
                <li class="door-3 charactor">&nbsp;</li>
                <li class="door-4 charactor">&nbsp;</li>
                <li class="door-5 charactor last">&nbsp;</li>
            </ul>
        </div>
    </div>
</div>