<div class="content step3">
    <div class="popup-treat-game">
        <div class="game-program"><img src="{{skin url='images/campaign/halloween/step3-game.png'}}" alt="" width="100%" height="100%" /></div>
        <div class="btn-spend">
            <h2>You have received <span class="points-value">10 points</span> which equals to <span class="money-value">$10</span> discount in your next order</h2>
            <button id="spend-my-points" class="btn btn-submit" type="button">Yes, spend my points now</button></div>
        <div class="treat-game-program">
            <ul>
                <li class="miss-door-1 active">
                    <div class="door">&nbsp;</div>
                    <p class="points-value">10 Points</p>
                </li>
                <li class="miss-door-2">
                    <div class="door">&nbsp;</div>
                    <p class="points-value">10 Points</p>
                </li>
                <li class="miss-door-3">
                    <div class="door">&nbsp;</div>
                    <p class="points-value">10 Points</p>
                </li>
                <li class="miss-door-4">
                    <div class="door">&nbsp;</div>
                    <p class="points-value">10 Points</p>
                </li>
                <li class="miss-door-5 last">
                    <div class="door">&nbsp;</div>
                    <p class="points-value">10 Points</p>
                </li>
            </ul>
        </div>
    </div>
</div>