<form action="<?php echo $this->getUrl('campaign/ajaxform/register') ?>" method="post">
    <div class="fieldset">
        <input type="hidden" name="success_url" value="">
        <input type="hidden" name="error_url" value="">

        <p class="required">* Required Fields</p>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label for="firstname" class="required"><em>*</em>First Name</label>
                        <div class="input-box">
                            <input type="text" id="firstname" name="firstname" value="" title="First Name" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field name-lastname">
                        <label for="lastname" class="required"><em>*</em>Last Name</label>
                        <div class="input-box">
                            <input type="text" id="lastname" name="lastname" value="" title="Last Name" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <label for="email_address" class="required"><em>*</em>Email Address</label>
                <div class="input-box">
                    <input type="email" spellcheck="false" name="email" id="email_address" value="" title="Email Address" class="input-text validate-email required-entry">
                </div>
            </li>

            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em>Password</label>
                    <div class="input-box">
                        <input type="password" name="password" id="password" title="Password" class="input-text required-entry validate-password">
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em>Confirm Password</label>
                    <div class="input-box">
                        <input type="password" name="confirmation" title="Confirm Password" id="confirmation" class="input-text required-entry validate-cpassword">
                    </div>
                </div>
            </li>
            <li class="control">
                <div class="input-box">
                    <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox">
                </div>
                <label for="is_subscribed">Sign Up for Newsletter</label>
            </li>
        </ul>
        <div class="remember-me-popup">
            <div class="remember-me-popup-head">
                <h3>What's this?</h3>
                <a href="#" class="remember-me-popup-close" title="Close">Close</a>
            </div>
            <div class="remember-me-popup-body">
                <p>Checking "Remember Me" will let you access your shopping cart on this computer when you are logged out</p>
                <div class="remember-me-popup-close-button a-right">
                    <a href="#" class="remember-me-popup-close button" title="Close"><span>Close</span></a>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            //<![CDATA[
            function toggleRememberMePopup() {
                var formParent = jQuery(this).parents('form:first');
                formParent.find('.remember-me-box a').toggleClass('hide');
                formParent.find('.remember-me-popup').toggleClass('show');
                return false;
            }
            var rememberMeToggleSetup = false;
            jQuery(document).ready(function(){
                if (!rememberMeToggleSetup) {
                    jQuery('.remember-me-box a, .remember-me-popup a').on('click', toggleRememberMePopup);
                    rememberMeToggleSetup = true;
                }
            });
            //]]>
        </script>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a style="cursor:pointer" class="back-link campaign-login"><small>« </small>Login</a></p>
        <button type="submit" title="Register" class="button"><span><span>Register</span></span></button>
    </div>
</form>

<form style="display:none" action="<?php echo $this->getUrl('customer/account/login/')?>" method="post" id="sc-login">
    <ul>
        <li>
            <input type="text" name="login_email" placeholder="Enter Your Email" title="Enter Your Email">
        </li>
        <li>
            <input type="password" name="login_password" placeholder="Password" title="Select Your Password">
        </li>
        <li style="text-align:right">
            <button title="Login" type="submit" style="border:0 none;background:green;padding:7px 15px;margin-top:20px;color:#fff"> Login </button>
        </li>
    </ul>
    <p><a href="<?php echo $this->getUrl('customer/account/forgotpassword/')?>">Forgot password?</a> | <a href="#" class="campaign-register">Register</a></p>
</form>
