<div class="newsletterPopup tp10" id="_sp7r">
    <form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post" id="newsletter-popup-2">
        <input type="text" name="email-2" id="newsletter-2" placeholder="Type your email here" title="<?php echo $this->__('Type your email here') ?>" class="input-text required-entry validate-email" />
        <button type="submit" title="<?php echo $this->__('Let me in') ?>" class="button"><span><span><?php echo $this->__('Let me in') ?></span></span></button>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup-2');
        //]]>



    </script>
</div>