<div class="form-subscribe">
    <form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
        <table border="0" cellspacing="0" cellpadding="0" style="margin: 0 auto;">
            <tbody><tr>
                <td><input type="text" name="email" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" /></td>
                <td style="vertical-align: top;width:1px;">
                    <button style="margin-left:5px" type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Get coupon') ?></span></span></button>
                </td>
            </tr>
            </tbody></table>
    </form>

</div>