<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup-5">
    <input type="text" name="email-5" id="newsletter-5" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" />
    <button type="submit" title="<?php echo $this->__('JOIN MAILING LIST') ?>" class="button"><span><span><?php echo $this->__('JOIN MAILING LIST') ?></span></span></button>
</form>
<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup-5');
    //]]>
</script>