<div class="newsletter-form">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup-11">
        <table border="0" cellspacing="0" cellpadding="0">
            <tbody><tr>
                <td><input type="text" name="email-11" id="newsletter-11" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" /></td>
                <td style="width:1px;">
                    <button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><span><span><?php echo $this->__('Join me') ?></span></span></button>
                </td>
            </tr>
            </tbody>

    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup-11');

    //]]>
</script>