<div class="newsletterPopup tp10" id="_sp7r">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup">
        <input type="text" name="email" id="newsletter" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" />
        <button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><span><span><?php echo $this->__('Join me') ?></span></span></button>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup');
        //]]>
    </script>
</div>

