<div class="newsletter-form">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup-3">
        <input type="text" name="email-3" id="newsletter-3" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" />
        <button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><span><span><?php echo $this->__('Join me') ?></span></span></button>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup-3');
        //]]>
    </script>
</div>

