<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-popup">
    <table border="0" cellspacing="0" cellpadding="0">
        <tbody><tr>
            <td><input style="width:100%;height:40px" type="text" name="email" id="newsletter" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" /></td>
            <td style="vertical-align: top;width:1px;"><button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><span><span><?php echo $this->__('Join me') ?></span></span></button></td>
        </tr>
        </tbody></table>
</form>
<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-popup');
    //]]>
</script>