<form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
    <p><input type="text" name="email"  placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" /></p>
    <p><button type="submit" title="<?php echo $this->__('JOIN MAILING LIST') ?>" class="button"><?php echo $this->__('JOIN MAILING LIST') ?></button></p>
</form>
