<form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
    <table border="0" cellspacing="0" cellpadding="0" style="width:100%;border-spacing: 25px;border-collapse: separate;">
        <tbody><tr>
            <td><input style="width:100%" type="text" name="email" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" /></td>
            <td style="width:1px;vertical-align: top"><button style="background:#fdff65" type="submit" title="<?php echo $this->__('Yes, let’s join') ?>" class="button"><span><span style="color:#000"><?php echo $this->__('Yes, let’s join') ?></span></span></button></td>
        </tr>
        </tbody></table>
</form>