<div class="newsletter-form">
    <form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
        <input type="text" name="email" id="newsletter-3" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" />
        <button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><span><span><?php echo $this->__('Join me') ?></span></span></button>
    </form>
</div>

