<div class="newsletter-form">
    <form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
        <table border="0" cellspacing="0" cellpadding="0">
            <tbody><tr>
                <td><input type="text" name="email" placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" /></td>
                <td style="width:1px;">
                    <button type="submit" title="<?php echo $this->__('Join me') ?>" class="button"><?php echo $this->__('Join me') ?></button>
                </td>
            </tr>
            </tbody>

    </form>
</div>
