<form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
    <input type="text" name="email"  placeholder="Enter your email" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" />
    <button type="submit" title="<?php echo $this->__('JOIN MAILING LIST') ?>" class="button"><span><span><?php echo $this->__('JOIN MAILING LIST') ?></span></span></button>
</form>
