<div class="newsletterPopup tp10" id="_sp7r">
    <form action="<?php echo $this->getUrl('campaign/ajaxform/subcriber') ?>" method="post">
        <input type="text" name="email" id="" placeholder="Type your email here" title="<?php echo $this->__('Type your email here') ?>" class="input-text required-entry validate-email" />
        <button type="submit" title="<?php echo $this->__('Let me in') ?>" class="button"><span><span><?php echo $this->__('Let me in') ?></span></span></button>
    </form>

</div>