<?php $idslider= $this->getSliderID();?>
<div class="content-header">
    <a href="#" onclick="TINY.box.hide();"></a>
    <h3>
        <?php echo $this->__("Copy and paste this into your HTML code wherever you want the widget to appear on your page.") ?>
    </h3>
</div>
<div class="content">
    <p>- Add code below to a template file</p>
    <textarea style="width:650px; height:32px;">
    $this->getLayout()->createBlock(bannerslider/default)->setTemplate(bannerslider/bannerslider.phtml)->setBannersliderId('<?php echo $idslider; ?>')->toHtml();
    </textarea>
    <p>- You can put a banner slider on a cms page. Below is an example which we put a banner slider with bannerslider_id is your_bannerslider_id on a cms page</p>
    <textarea style="width:650px; height:32px;">
    {{block type="bannerslider/default" name="bannerslider.bannerslider" template="bannerslider/bannerslider.phtml" bannerslider_id="<?php echo $idslider; ?>"}}
    </textarea>
    <p>- Please copy and paste the code below on one of xml layout files where you want to show the banner. Please replace the your_bannerslider_ids variable with your own bannerslider Id</p>
    <textarea style="width:650px; height:55px;">
    <block type="bannerslider/default" name="bannerslider.bannerslider" template="bannerslider/bannerslider.phtml">
        <action method="setBannersliderId"><bannerslider_id><?php echo $idslider; ?></bannerslider_id></action>
    </block>
    </textarea>
    <p>- Below is an example to show a banner slider with your_bannerslider_id on the left of the category page.</p>
    <textarea style="width:650px; height:100px;">
        <?xml version="1.0"?>
        <layout version="0.1.0">
            <catalog_category_default>
                <reference name="left">
                    <block type="catalog/navigation" name="catalog.leftnav" after="currency" template="catalog/navigation/left.phtml"/>
                    <block type="bannerslider/default" name="bannerslider.block" template="bannerslider/bannerslider.phtml">
                        <action method="setBannersliderId"><bannerslider_id><?php echo $idslider; ?></bannerslider_id></action>
                    </block>
                </reference>
            </catalog_category_default>
        </layout>
    </textarea>
</div>

<div id="messages">
    <ul class="messages" id="copied" style="display: none">
        <li class="success-msg">
            <span><?php echo $this->__('The code has been copied to your clipboard.') ?></span>
        </li>
    </ul>
</div>
<div class="userguide">
    <h4><span></span> <?php echo $this->__("You can adjust the value of data-width and data-height for each widget.") ?></h4>
    <h4><span></span> <?php echo $this->__('You can also place many widgets in a same page.') ?></h4>
</div>
<style>
    #tinycontent .content-header a{
        background-image: url("<?php echo $this->getSkinUrl('css/magestore/bannerslider/images/ui-icons_888888_256x240.png') ?>");
        background-repeat: no-repeat;
        background-position: -94px -127px;
        display: inline-block;width: 20px; height: 20px;
    }
    #tinycontent .userguide{
        margin: 10px 0px;
    }
    #tinycontent #copy-button{padding: 3px;}

    .content{font-weight: normal; width: 600px; font-size: 11px;}
    .content p{font-weight: bold; font-size: 12px; color:#f6841f;}
</style>
