<div class="row">
    <div class="image-left col-lg-6 col-md-6 col-sm-6 col-xs-12"><img src="{{skin url='images/campaign/img-left.png'}}" alt="Summer holiday" width="100%" height="100%" /></div>
    <div class="content-right col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <h3 class="heading-title">BIG SALE</h3>
        <div class="sub-title"><span class="number-percent">10%</span><span class="text-percent">COUPON code now!</span></div>
        <span>{{block type="campaign/countdown" locate="popup"}}</span>
        <form id="email-campaign-summer" class="email-campaign" action="" method="post">
            <div id="demo_img" class="top-demo">
                <div class="input-box"><input id="name-customer" class="input-text required-entry" title="* Enter your name to join" type="text" name="name" value="" /></div>
                <div class="input-box"><input id="email-customer" class="input-text required-entry validate-email" title="* Enter your email to join" type="text" name="email" value="" /></div>
                <div class="actions"><button id="submit-info" class="button button-submit" type="submit"><span><span>Get Coupon Code</span></span></button> <span class="loading" style="display: none;"> <img src="{{skin url='images/campaign/loading.gif'}}" alt=" alt=" width="20" height="20" /> </span></div>
                <div class="error-message" style="color: red; display: none; font-weight: normal; font-size: 12px;">&nbsp;</div>
            </div>
        </form></div>
</div>