<?php
/**
 * TIT modified 7/9/2015
 */
$banners = $this->getBannerhomepages();
?>
<!-- campaign/bannerhomepage.phtml -->
<?php if(count($banners) > 0): ?>
    <div class="super-campaign-home-slide">
        <div id="home-banner-slide" class="owl-carousel">
            <?php foreach ($banners as $bann):
                if ($bann->getInputBannerhomepage() != ''):
                    /*Tit edit*/
                    $link = $bann->getLinkAttached();
                    if(strpos($link, 'www.') === 0){
                        $link = '//'.$link;
                    }
                    /*end Tit*/
                    ?>
                    <div>
                        <a href="<?php echo $link; ?>"
                           target="_blank">
                            <?php //if ($bann->getStatus() == 1): ?>
                            <img
                                src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $bann->getInputBannerhomepage(); ?>"
                                alt=""/>
                            <?php //endif; ?>
                        </a>
                    </div>
                <?php endif;?>
            <?php endforeach; ?>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('#home-banner-slide').owlCarousel({
                navigation : true, // Show next and prev buttons
                slideSpeed : 500,
                paginationSpeed : 600,
                singleItem:true,
                autoPlay: true
            });
        });
    </script>
<?php endif; ?>

